# Generated by Django 6.0.4 on 2026-04-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('received_date', models.DateTimeField()),
                ('is_key', models.BooleanField(default=False)),
                ('importance_score', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailcategory')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='emails.email')),
            ],
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'is_key'], name='emails_emai_user_id_fc01d4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['gmail_id'], name='emails_emai_gmail_i_e339e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtag',
            unique_together={('email', 'category')},
        ),
    ]
